from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand
from django.db import connection

from users.models import Artist, Song


class Command(BaseCommand):
    help = "Import KKBOX artists and songs from CSV files generated by the recommender pipeline"

    def add_arguments(self, parser):
        parser.add_argument(
            "--artifacts-dir",
            type=Path,
            default=None,
            help="Path to recommender artifacts directory (default: settings.RECOMMENDER_ARTIFACTS_DIR)",
        )

    def handle(self, *args, **options):
        artifacts_dir = options["artifacts_dir"] or settings.RECOMMENDER_ARTIFACTS_DIR

        artist_csv = artifacts_dir / "artist_id_map_small.csv"
        song_csv = artifacts_dir / "song_for_db_small.csv"

        # --- 檢查檔案是否存在 ---
        if not artist_csv.exists():
            self.stderr.write(self.style.WARNING(
                f"artist_id_map_small.csv not found at {artist_csv}, skipping import. "
                f"Run stage_04c_export_db_subset.py in recommender first."
            ))
            return
        if not song_csv.exists():
            self.stderr.write(self.style.WARNING(
                f"song_for_db_small.csv not found at {song_csv}, skipping import. "
                f"Run stage_04c_export_db_subset.py in recommender first."
            ))
            return

        # --- 如果資料庫已有資料，跳過 ---
        existing_artists = Artist.objects.count()
        existing_songs = Song.objects.count()
        if existing_artists > 0 and existing_songs > 0:
            self.stdout.write(self.style.SUCCESS(
                f"Database already has {existing_artists} artists and {existing_songs} songs, skipping import."
            ))
            return

        cursor = connection.cursor()

        # 暫時關閉外鍵檢查和唯一性檢查，大幅加速 LOAD DATA
        cursor.execute("SET FOREIGN_KEY_CHECKS = 0")
        cursor.execute("SET UNIQUE_CHECKS = 0")

        try:
            # --- Import Artists via LOAD DATA LOCAL INFILE ---
            self.stdout.write("Importing artists via LOAD DATA LOCAL INFILE...")
            cursor.execute("ALTER TABLE users_artist DISABLE KEYS")
            cursor.execute("""
                LOAD DATA LOCAL INFILE %s
                INTO TABLE users_artist
                CHARACTER SET utf8mb4
                FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
                LINES TERMINATED BY '\\n'
                IGNORE 1 LINES
                (id, artist_name)
                SET artist_image = NULL,
                    language = '',
                    created_at = NOW()
            """, [str(artist_csv)])
            cursor.execute("ALTER TABLE users_artist ENABLE KEYS")

            artist_count = Artist.objects.count()
            self.stdout.write(self.style.SUCCESS(f"Imported {artist_count} artists."))

            # --- Import Songs via LOAD DATA LOCAL INFILE ---
            self.stdout.write("Importing songs via LOAD DATA LOCAL INFILE...")
            cursor.execute("ALTER TABLE users_song DISABLE KEYS")
            cursor.execute("""
                LOAD DATA LOCAL INFILE %s
                INTO TABLE users_song
                CHARACTER SET utf8mb4
                FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
                LINES TERMINATED BY '\\n'
                IGNORE 1 LINES
                (@song_id, song_title, artist_id, artist_name, language)
                SET id = @song_id,
                    album_name = '',
                    song_image = NULL,
                    release_date = NULL,
                    created_at = NOW()
            """, [str(song_csv)])

            # 刪除 song_id < 0 的無效資料（原始 CSV 中約 898 筆）
            cursor.execute("DELETE FROM users_song WHERE id < 0")
            deleted = cursor.rowcount

            cursor.execute("ALTER TABLE users_song ENABLE KEYS")

            song_count = Song.objects.count()
            self.stdout.write(self.style.SUCCESS(
                f"Imported {song_count} songs (deleted {deleted} invalid rows with id < 0)."
            ))
        finally:
            # 確保恢復檢查，即使出錯也不會留在不安全狀態
            cursor.execute("SET FOREIGN_KEY_CHECKS = 1")
            cursor.execute("SET UNIQUE_CHECKS = 1")
