# Generated by Django 6.0.3 on 2026-04-17 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_playlist_playlistsong'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(max_length=50)),
                ('algorithm_version', models.CharField(blank=True, default='', max_length=50)),
                ('generated_at', models.DateTimeField()),
                ('total_size', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.SmallIntegerField()),
                ('score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.recommendationbatch')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_entries', to='users.song')),
            ],
            options={
                'ordering': ['rank'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'rank'), name='unique_batch_rank'), models.UniqueConstraint(fields=('batch', 'song'), name='unique_batch_song')],
            },
        ),
    ]
