# Generated by Django 6.0.3 on 2026-04-25 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_recommendationbatch_recommendationitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('watch_seconds', models.IntegerField()),
                ('source', models.CharField(choices=[('RECOMMENDATION', '推薦系統'), ('SEARCH', '主動搜尋'), ('PLAYLIST', '播放清單'), ('ONBOARDING', '冷啟動預選'), ('FRIEND', '好友也在聽')], default='RECOMMENDATION', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='users.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-played_at'], name='users_histo_user_id_d44561_idx')],
            },
        ),
    ]
