# Generated by Django 6.0.3 on 2026-04-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usersonglike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='source',
            field=models.CharField(choices=[('RECOMMENDATION', '推薦系統'), ('SEARCH', '主動搜尋'), ('PLAYLIST', '播放清單'), ('ONBOARDING', '冷啟動預選'), ('FRIEND', '好友也在聽')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='usersonglike',
            index=models.Index(fields=['user', 'song', 'is_liked'], name='users_users_user_id_9ada4b_idx'),
        ),
    ]
