# Generated by Django 6.0.3 on 2026-04-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_song_fulltext_index'),
        ('users', '0007_alter_history_source_and_more'),
    ]

    operations = [
    ]
