# Generated by Django 6.0.3 on 2026-05-09 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20260426_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersonglike',
            name='is_liked',
            field=models.BooleanField(help_text='True: 喜歡，False: 不喜歡'),
        ),
        migrations.CreateModel(
            name='UserSongAffinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_watch_seconds', models.IntegerField(default=0)),
                ('skip_count', models.IntegerField(default=0)),
                ('is_favorited', models.BooleanField(default=False)),
                ('like_state', models.SmallIntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_affinities', to='users.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affinities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-score'], name='users_users_user_id_269145_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'song'), name='unique_user_song_affinity')],
            },
        ),
    ]
