# Generated by Django 6.0.3 on 2026-05-17 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_usersonglike_is_liked_usersongaffinity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKKBoxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msno', models.CharField(max_length=255, unique=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kkbox_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
