# Generated by Django 6.0.3 on 2026-05-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_usersonglike_is_liked_usersongaffinity'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='True: 使用者主動隱藏這筆歷史紀錄（前端不顯示，但 row 仍保留）'),
        ),
    ]
