# Generated by Django 6.0.3 on 2026-05-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_history_is_hidden'),
        ('users', '0010_userkkboxprofile'),
    ]

    operations = [
    ]
