# Generated by Django 6.0.3 on 2026-06-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_seed_playlist_icons'),
        ('users', '0014_friendrequest'),
    ]

    operations = [
    ]
